version: 2
updates:
  # Check for frontend React/Vite updates
  - package-ecosystem: "npm"
    directory: "/grievance"
    schedule:
      interval: "weekly"

  # Check for backend Python/FastAPI updates
  - package-ecosystem: "nuget"
    directory: "/grievance-b"
    schedule:
      interval: "weekly"